apiVersion: apps/v1
kind: Deployment
metadata: 
  name: circle-project  
  labels: 
    name: "circle-project"
  annotations:
    # force policy will ensure that deployment is updated
    # even when tag is unchanged (latest remains)
    keel.sh/policy: major
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 30s"
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: circle-project
  template:
    metadata:
      name: circle-project
      labels:
        app: circle-project
    spec:     
      containers:                    
        - image: suraj18/circleci_project:latest
          imagePullPolicy: Always # this is required to force pull image     
          name: circle-project
          ports:
            - containerPort: 80
              #livenessProbe:
              # httpGet:
              #path: /
              #port: 8500
              #initialDelaySeconds: 10
              #timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: circle-project
spec:
  selector:
    app: circle-project
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: circle-project
spec:
  rules:
  - host: circle-project.example.com 
    http:
      paths:
      - path: /
        backend:
          serviceName: circle-ci
          servicePort: 80
